#spring:
#  profiles:
#    active: test
server:
  port: 8085
spring:
  cloud:
    bus:
      enabled: false
#  rabbitmq:
#    host: "localhost"
#    username: "guest"
#    password: "guest"
#    port: 5672
  application:
    name: order-service
  config:
    import: configserver:http://localhost:8889
management:
  endpoints:
    web:
      exposure:
        include: "*"